version: "3.3"
services:
  app:
    image: weather-app:latest
    ports:
      - 8080:8080
    restart : always
    env_file: # https://github.com/docker/compose/issues/4223
      - .env
    environment:
      - DEBUG=false